'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { buildManagedBlock, buildUserLanguageBlock } = require('../../src/cli/lang-policy');

test('入口规则明确区分 hook 反馈与真实用户确认', () => {
  const entry = fs.readFileSync(path.resolve(__dirname, '../../skills/using-spec-first/SKILL.md'), 'utf8');
  expect(entry).toContain('都不是新的用户授权');
  expect(entry).toContain('必须等待实际回复');
});

test.each(['zh', 'en'])('%s 项目级与用户级指令禁止默认追加署名', (lang) => {
  for (const render of [buildManagedBlock, buildUserLanguageBlock]) {
    const content = render(lang);
    expect(content).toContain(lang === 'zh' ? '禁止自动加入' : 'Never automatically add');
    expect(content).toContain('co-author');
    expect(content).toContain(lang === 'zh' ? '当前请求中明确要求' : 'current turn');
  }
});

test.each([
  'spec-commit-push-pr/SKILL.md',
  'spec-commit-push-pr/references/pr-description-writing.md',
  '_shared/references/html-rendering.md',
  'spec-plan/references/html-rendering.md',
  'spec-brainstorm/references/html-rendering.md',
  'spec-ideate/references/html-rendering.md',
  'spec-ideate/references/ideation-sections.md',
  'spec-explain/references/explainer-html.md',
  'spec-explain/references/destinations.md',
  'spec-dogfood/references/dogfood-report-template.md',
])('%s 不要求自动署名或宣传页脚', (file) => {
  const content = fs.readFileSync(path.resolve(__dirname, '../../skills', file), 'utf8');
  expect(content).not.toMatch(/Built with \[Spec-First\]|plain-text Spec-First footer|required footer content|Generated by `spec-|Composed .+ by spec-|composition-signal|keep the composition footer/);
});
